clinical_trials/urls.py
#-*- coding: utf-8 -*-
"""
Url for clinical_trials app.
"""
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from clinical_trials import views

urlpatterns = patterns(
    '',
    url(
        r'^public/(?P<rbr>[-\w]+)/$',
            views.PublicClinicalTrialDetailView.as_view(),
        name='clinical_trial_detail_public'),

    url(
        r'^(?P<pk>\d+)/$',
        login_required(
            views.ClinicalTrialDetailView.as_view()),
        name='clinical_trial_detail'),

    url(
        r'^download/(?P<rbr>[-\w]+)/$',
            views.ClinicalTrialDownloadView.as_view(),
        name='clinical_trial_download'),

    url(
        r'^add/$',
        login_required(
            views.ClinicalTrialAddView.as_view()),
        name='clinical_trial_add'),

    url(
        r'^(?P<pk>\d+)/delete/$',
        login_required(
            views.ClinicalTrialDeleteView.as_view()),
        name='clinical_trial_delete'),

    url(
        r'^(?P<pk>\d+)/edit/$',
        login_required(
            views.ClinicalTrialEditListView.as_view()),
        name='clinical_trial_edit_list'),


    url(
        r'^(?P<pk>\d+)/group/management/$',
        login_required(
            views.ClinicalTrialGroupManagementView.as_view()),
        name='clinical_trial_group_manage'),

    url(
        r'^(?P<pk>\d+)/edit/identification/$',
        login_required(
            views.ClinicalTrialIdentificationView.as_view()),
        name='clinical_trial_edit_identification'),

    url(
        r'^(?P<pk>\d+)/edit/sponsors/$',
        login_required(
            views.ClinicalTrialSponsorsView.as_view()),
        name='clinical_trial_edit_sponsors'),

    url(
        r'^(?P<pk>\d+)/edit/health-conditions/$',
        login_required(
            views.ClinicalTrialHealthConditionView.as_view()),
        name='clinical_trial_edit_health_conditions'),

    url(
        r'^(?P<pk>\d+)/edit/interventions/$',
        login_required(
            views.ClinicalTrialInterventionView.as_view()),
        name='clinical_trial_edit_interventions'),

    url(
        r'^(?P<pk>\d+)/edit/recruitment/$',
        login_required(
            views.ClinicalTrialRecruitmentView.as_view()),
        name='clinical_trial_edit_recruitment'),

    url(
        r'^(?P<pk>\d+)/edit/study-type/$',
        login_required(
            views.ClinicalTrialStudyTypeView.as_view()),
        name='clinical_trial_edit_study_type'),

    url(
        r'^(?P<pk>\d+)/edit/outcomers/$',
        login_required(
            views.ClinicalTrialOutcomesView.as_view()),
        name='clinical_trial_edit_outcomes'),

    url(
        r'^(?P<pk>\d+)/edit/contacts/$',
        login_required(
            views.ClinicalTrialContactsView.as_view()),
        name='clinical_trial_edit_contacts'),

    url(
        r'^(?P<pk>\d+)/edit/attachments/$',
        login_required(
            views.ClinicalTrialAttachmentsView.as_view()),
        name='clinical_trial_edit_attacments'),

    url(
        r'^(?P<pk>\d+)/edit/send/$',
        login_required(
            views.ClinicalTrialSendView.as_view()),
        name='clinical_trial_edit_send'),

    url(
        r'^manage/$',
        login_required(
            views.ClinicalTrialManageView.as_view()),
        name='clinical_trial_admin_manage'),

    url(
        r'ct-contacts/(?P<clinical_trial_pk>\d+)/add/(?P<contact_type>P|S|W)$',
        login_required(
            views.ClinicalTrialCreateContact.as_view()),
        name='clinical_trial_add_contact'),
    url(
        r'^field-revisor-screen/(?P<clinical_trial_id>\d+)/(?P<content_type_id>\d+)/(?P<content_id>\d+)/(?P<field_name>\w+)/$',
        login_required(
            views.ClinicalTrialFieldRevisorView.as_view()),
        name='field_revisor_screen'),
    url(
        r'^field-registrant-screen/(?P<clinical_trial_id>\d+)/(?P<content_type_id>\d+)/(?P<content_id>\d+)/(?P<field_name>\w+)/$',
        login_required(
            views.ClinicalTrialFieldRegistrantView.as_view()),
        name='field_registrant_screen'),
    url(
        r'^add-workflow-field-observation/(?P<clinical_trial_id>\d+)/(?P<content_type_id>\d+)/(?P<content_id>\d+)/(?P<field_name>\w+)/$',
        login_required(
            views.ClinicalTrialAddFieldObservationView.as_view()),
        name='add_workflow_field_observation'),
    url(
        r'^list-workflow-field-observation/(?P<clinical_trial_id>\d+)/(?P<content_type_id>\d+)/(?P<content_id>\d+)/(?P<field_name>\w+)/$',
        login_required(
            views.ClinicalTrialListFieldObservationView.as_view()),
        name='list_workflow_field_observation'),
    url(
        r'^list-workflow-observations/(?P<clinical_trial_id>\d+)/$',
        login_required(
            views.ClinicalTrialListObservationsView.as_view()),
        name='list_workflow_pending_observations'),
    url(
        r'^list-field-changes-log/(?P<clinical_trial_id>\d+)/(?P<content_type_id>\d+)/(?P<content_id>\d+)/(?P<field_name>\w+)/$',
        login_required(
            views.ClinicalTrialListFieldChangeHistoryView.as_view()),
        name='list_field_changes_log'),

    url(
        r'^(?P<pk>\d+)/history/$',
        login_required(
            views.ClinicalTrialHistoryView.as_view()),
        name='clinicaltrial_history'),

    url(
        r'no-holder-cts/$',
        login_required(
            views.NoholderCTView.as_view()),
        name='no_holder_cts_list'),

    url(
        r'descriptors-cid-10-search/$',
        login_required(
            views.DescriptorsCid10SearchJsonView.as_view()),
        name='descriptors_cid10_search'),

    url(
        r'descriptors-decs-search/$',
        login_required(
            views.DescriptorsDeCSSearchJsonView.as_view()),
        name='descriptors_decs_search'),

    url(
        r'^accept-in-group/(?P<pk>\d+)/$',
        login_required(
            views.ClinicalTrialAcceptInGroupView.as_view()),
        name='clinical_trial_accept_in_group'),

    url(
        r'^check-for-changes/(?P<pk>\d+)/$',
        login_required(
            views.ClinicalTrialChangeStudyStatusView.as_view()),
        name='clinical_trial_check_for_changes'),
    url(
        r'^check-for-changes/(?P<pk>\d+)/step2/$',
        login_required(
            views.ClinicalTrialCheckForChangesView.as_view()),
        name='clinical_trial_check_for_changes_step2'),
    url(
        r'^snapshot-view/(?P<pk>\d+)/$',
        views.ClinicalTrialSnapshotView.as_view(),
        name='clinicaltrial_snapshot_view'),

)

cmsplugin_news/urls.py
from django.conf.urls import patterns, url, include

from . import feeds
from . import views


urlpatterns = patterns('django.views.generic.date_based',
    url(r'^$',
        views.ArchiveIndexView.as_view(), name='news_archive_index'),

    url(r'^(?P<year>\d{4})/$',
        views.YearArchiveView.as_view(), name='news_archive_year'),

    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/$',
        views.MonthArchiveView.as_view(), name='news_archive_month'),

    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$',
        views.DayArchiveView.as_view(), name='news_archive_day'),

    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$',
        views.DetailView.as_view(), name='news_detail'),

    url(r'^feed/$', feeds.NewsFeed())
)

rebec/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib import admin
from django.conf import settings
from django.contrib.auth.views import logout
from registration.views import register
from login.forms import UserCreationForm, AuthenticationForm
admin.autodiscover()
from django.core.urlresolvers import reverse_lazy
from administration.views import DashboardView, HelpView, AccessibilityView
from django.contrib.auth.decorators import login_required
from portal import views as view_portal
from login.views import ResendActivationEmail, login

from django.conf.urls.i18n import i18n_patterns
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',
    url(r'^dashboard/$', login_required(DashboardView.as_view()), name="home"),
    url(r'^accessibility/$', login_required(AccessibilityView.as_view()), name="accessibility"),
    url(r'^i18n/setlang', view_portal.set_language),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^login/$', login, {'template_name': 'registration/login.html', 'authentication_form': AuthenticationForm}, name='login'),
    url(r'^logout/$', logout, {'template_name': 'registration/logout.html',
                               'next_page': '/'}, name='logout'),
    url(r'^register/$',register, {'backend': 'registration.backends.default.DefaultBackend', 'form_class': UserCreationForm},name='registration_register'),
    url(r'^administration/', include('administration.urls')),
    url(r'^clinicaltrials/', include('clinical_trials.urls')),
    url(r'^import-export-config/', include('import_export_config.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^news/', include('cmsplugin_news.urls')),
    url(r'^registered/$',
        view_portal.ClinicalTrialRegisteredList.as_view(),
        name='ct_registered_list'),
    url(r'^recruiting/$',
        view_portal.ClinicalTrialRecruitingList.as_view(),
        name='ct_recruiting_list'),
    url(r'^scoreboard/$',
        view_portal.ClinicalTrialSummaryView.as_view(),
        name='ct_summay'),
    url(r'^search/$',
        view_portal.SearchView.as_view(),
        name='search'),
    # url(r'^help/$',
    #     HelpView.as_view(), name=u'home_help'),
    url(r'^resend-activation/$', (ResendActivationEmail.as_view()), name="resend_activation_email"),
    url(r'', include('registration.backends.default.urls')),
    url(r'', include('django.contrib.auth.urls')),
)

urlpatterns += staticfiles_urlpatterns()

urlpatterns += i18n_patterns('',
    url(r'^', include('cms.urls')),
)


handler404 = 'portal.views.handler404'
handler500 = 'portal.views.handler500'
handler403 = 'portal.views.handler403'

from django.conf import settings
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
    )

login/models.py
import datetime
import hashlib
import random
import re
from django.db import models
from django.db.models import Count, Q
from django.contrib.auth.models import AbstractUser
from django.core import validators
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from administration.models import CTGroupUser, Country


class RebecUser(AbstractUser):
    """
    Recec user model.
    """
    GENDER_CHOICES = (
        (1, _('Male')),
        (2, _('Female')),
    )

    RACE_CHOICES = (
        (1, _('White')),
        (2, _('Yellow')),
        (3, _('Indigenous')),
        (4, _('Brown')),
        (5, _('Black')),
    )

    name = models.CharField(
        _('name'),
        max_length=100)
    gender = models.IntegerField(
        _('gender'),
        choices=GENDER_CHOICES,)
    race = models.IntegerField(
        _('race'),
        choices=RACE_CHOICES)
    ocuppation = models.IntegerField(
        _('ocuppation'),
        blank=True,
        null=True)
    passport = models.CharField(
        _('Passport'),
        blank=True,
        null=True,
        max_length=14,
        help_text=_("Enter the number of your passport."))
    cpf =  models.CharField(
        _('CPF'),
        blank=True,
        null=True,
        max_length=14,
        help_text=_('The cpf has 11 digits.'))

    country = models.ForeignKey(Country, default=u'BR')

    REQUIRED_FIELDS = ['name', 'email', 'gender', 'race', 'country', 'passport', 'cpf',]

    def __unicode__(self):
        """
        Return username.
        """
        return self.username

    def is_registrant(self):
        return self.groups.filter(name=u'registrant').exists()

    def is_registrant_administrator(self):
        return (
            self.groups.filter(name=u'registrant').exists()
            and self.ctgroups.filter(
                    type_user=CTGroupUser.TYPE_ADMINISTRATOR
                ).exists()
            )

    def is_manager(self):
        return self.groups.filter(name=u'manager').exists()

    def is_reviser(self):
        return self.groups.filter(name=u'reviser').exists()

    def is_evaluator(self):
        return self.groups.filter(name=u'evaluator').exists()

    def is_administrador(self):
        return self.groups.filter(name=u'administrador').exists()

    def is_editor(self):
        return self.groups.filter(name=u'editor').exists()

    def get_pendencies(self):
        from administration.models import Institution, CTGroup, CTGroupUser
        from workflows.models import StateObjectRelation, State
        from clinical_trials.models import ClinicalTrial
        total = 0
        if self.is_administrador():
            moderation_status_cts = StateObjectRelation.objects.filter(
                                    state__pk__in=\
                                    (State.STATE_AGUARDANDO_MODERACAO,
                                     State.STATE_EM_MODERACAO_RESUBMETIDO)
                                ).values_list('content_id', flat=True)
            #Removed from the panel number red circle for critical performance reasons
            
            institution_pending1 = Institution.objects.filter(
                status=Institution.STATUS_MODERATION
            ).filter(
                Q(sponsor_items__clinical_trial__pk__in=moderation_status_cts)
            ).values_list(u'pk', flat=True)

            institution_pending2 = Institution.objects.filter(
                status=Institution.STATUS_MODERATION
            ).annotate(
                number_of_ctgroups=Count('ctgroups'),
            ).filter(
                number_of_ctgroups__gt=0
            ).values_list(u'pk', flat=True)

            if institution_pending1.exists() or institution_pending2.exists():
                total += len(set(tuple(institution_pending1) + tuple(institution_pending2)))

            group_institution_pending = CTGroup.objects.filter(
                    status_institution=CTGroup.STATUS_INSTITUTION_PENDING,
                    institution__status=Institution.STATUS_ACTIVE,
                    status=CTGroup.STATUS_ACTIVE,
                    ).exists()
            if group_institution_pending:
                total += CTGroup.objects.filter(
                    status_institution=CTGroup.STATUS_INSTITUTION_PENDING,
                    institution__status=Institution.STATUS_ACTIVE,
                    status=CTGroup.STATUS_ACTIVE,
                    ).count()

            group_administrator_pending = CTGroupUser.objects.filter(
                status=CTGroupUser.STATUS_PENDING_APROV_ADM).exists()

            if group_institution_pending:
                total += CTGroupUser.objects.filter(
                status=CTGroupUser.STATUS_PENDING_APROV_ADM).count()

        if self.is_registrant():
            resubmetido = StateObjectRelation.objects.filter(
                state__pk=State.STATE_RESUBMETIDO).values_list(u'content_id', flat=True)

            revisando_preenchimento = StateObjectRelation.objects.filter(
                state__pk=State.STATE_REVISANDO_PREENCHIMENTO).values_list(u'content_id', flat=True)

            revisando_preenchimento_resubmetido = StateObjectRelation.objects.filter(
                state__pk=State.STATE_REVISAO_PREENCHIMENTO_RESUBMETIDO).values_list(u'content_id', flat=True)


            cts = ClinicalTrial.objects.filter(
                    Q(pk__in=revisando_preenchimento) | Q(pk__in=resubmetido) | Q(pk__in=revisando_preenchimento_resubmetido)
                ).filter(holder=self, user=self)
            if cts.exists():
                total += cts.count()

            group_adm = CTGroup.objects.filter(
                users__user=self, users__type_user='a'
            )
            if group_adm.exists():
                if CTGroupUser.objects.filter(ct_group=group_adm).filter(status=1).exists():
                    total += CTGroupUser.objects.filter(
                    ct_group=group_adm).filter(status=1).count()
                if CTGroupUser.objects.filter(ct_group=group_adm).filter(status=4).exists():
                    total += CTGroupUser.objects.filter(
                        ct_group=group_adm).filter(status=4).count()
        return total


#Make the email field required
RebecUser._meta.get_field(u'email').blank = False

default_country_clean = RebecUser._meta.get_field(u'country').clean
def __clean_country(raw_value, *args, **kwargs):
    return Country.objects.get(pk=raw_value)
def _clean_country(*args, **kwargs):
    import sys
    if 'createsuperuser' in sys.argv:
        return __clean_country(*args, **kwargs)
    return default_country_clean(*args, **kwargs)
RebecUser._meta.get_field(u'country').clean = _clean_country

templates/clinical_trials/approve_in_group.html
{% extends "administration/base_administration.html" %}
{% load i18n %}
{% block breadcrumbs %}
{{ block.super }}
<li class="formTab">
    <div class="selected">
        {% trans "Approve Trial in Group" %} {{ trial.group.name }}
    </div>
</li>
{% endblock %}
{% block administration_content %}
<h1>{% trans "Approve Trial in Group" %} {{ trial.group.name }}</h1>
<hr />
<form action="." method="POST">
    {% csrf_token %}
    <p class="message">{% trans "Confirm this trial in the group" %} {{ trial.group.name }}?</p>
    <input type="submit" value="{% trans 'Yes' %}" name="accept" class="confirm_delete">
    <input type="submit" value="{% trans 'No' %}" name="decline" class="confirm_delete">
</form>
{% endblock administration_content %}

templates/clinical_trials/clinical_trial_create_contact.html
{% extends "administration/base_administration.html" %}
{% load i18n static %}
{% block breadcrumbs %}
{{ block.super }}
<li class="formTab">
    <div class="selected">
        {% trans "Create Contact" %}
    </div>
</li>
{% endblock %}
{% block administration_content %}
<h1>{% trans 'Create a new contact' %}</h1>
<hr/>
<form  class="form_ct" action="" method="post">{% csrf_token %}
    {% include 'base/field_wrapper.html' with field=form.institution %}

    {% include 'base/field_wrapper.html' with field=form.first_name %}

    {% include 'base/field_wrapper.html' with field=form.middle_name %}

    {% include 'base/field_wrapper.html' with field=form.last_name %}

    {% include 'base/field_wrapper.html' with field=form.email %}

    <div class="fieldWrapper">
        <label>{% trans 'Search for address' %}</label><br />
        <div class="input">
            <input type="text" id="address_search">
        </div>
    </div>

    {% include 'base/field_wrapper.html' with field=form.address %}

    {% include 'base/field_wrapper.html' with field=form.city %}

    {% include 'base/field_wrapper.html' with field=form.state %}

    {% include 'base/field_wrapper.html' with field=form.country %}

    {% include 'base/field_wrapper.html' with field=form.postal_code %}

    {% include 'base/field_wrapper.html' with field=form.phone %}
    <div class="submit-line">
    <p>{{ message }}</p>
    <input type="hidden" name="confirm", value="yes"/>
    
      <input type="submit" value="{% trans 'Confirm' %}" class="button" />
      <a class="button_gray" href="{{ cancel_url }}">{% trans 'No' %}</a>
    </div>
</form>

<script src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false"></script>
<script type="text/javascript" src="{% static 'js/plugins/jquery.geocomplete.min.js' %}"></script>
<script type="text/javascript">
    $("#address_search").geocomplete()
      .bind("geocode:result", function(event, result){
          var search_result = {};
          $.each(result.address_components, function(index, object){
              var name = object.types[0];
              search_result[name] = object.long_name;
              search_result[name + "_short"] = object.short_name;
          });
          $('#id_state').val(search_result.administrative_area_level_1);
          $('#id_city').val(search_result.locality);
          var address = search_result.route;
          if(search_result.street_number) {
            address = address + ' ' + search_result.street_number;
          }
          if(search_result.neighborhood) {
            address = address + ', ' + search_result.neighborhood;
          }
          $('#id_address').val(address);
          $('#id_country').val(search_result.country_short);
    });

  </script>
<script type="text/javascript">
$(document).ready(function(){    
    $("#id_postal_code").mask("99.999-999");
});
</script>
{% endblock administration_content %}

{% block extrascripts %}
{{ block.super }}

<script type="text/javascript" src="{% static 'js/maskinput.js' %}"/></script>
    <script type="text/javascript">
        $('span.field-help, img.field-error').tooltip({'trigger': 'click'});
        $('.field-error').parents('.fields-wrapper').addClass('with-error');
        $('.field-error').parents('.input').addClass('with-error');
    </script>
    <script type="text/javascript">
    function get_url_parameters (term, page, context) {
            var field_id = jQuery(this).data('field_id'),
                res = {
                    'term': term,
                    'page': page,
                    'context': context,
                    'clinical_trial_id': "{{ clinical_trial_pk }}"
                };
            if (field_id) {
                res['field_id'] = field_id;
            }
            return res;
        }
    </script>
{% endblock %}

{% block extrastyle %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/clinical_trials.css' %}">
    <style type="text/css">
        div.fields-wrapper.with-error, div.input.with-error {
            background-color: #EBC0D0;
            border: 1px solid #000000;
        }
        .fieldWrapper {
            width: 60%;
        }
        .input {
            width: 100%;
        }
    </style>

{% endblock %}

templates/clinical_trials/clinical_trial_group_management_form.html
{% extends "administration/base_administration.html" %}
{% load i18n %}

{% block breadcrumbs %}
{{ block.super }}
<li class="formTab">
    <div class="selected">
        {% trans "Group Management" %}
    </div>
</li>
{% endblock %}
{% block administration_content %}
<h1>{% trans "Group Management" %}</h1>
<hr />
<form method="post" class="group">{% csrf_token %}
    {{ form.as_p }}
    <br />
    <input class="button" type="submit" value="{% trans 'Save' %}" />
</form>

{% endblock administration_content %}

templates/clinical_trials/clinical_trial_without_holder_list.html
{% extends "administration/base_administration.html" %}
{% load i18n %}
{% block breadcrumbs %}
{{ block.super }}
<li class="formTab">
    <div class="selected">
        {% trans "Clinical Trials" %}
    </div>
</li>
{% endblock %}
{% block administration_content %}
    <h1>{% trans "Clinical trials without current holder" %}</h1>
    <hr />
    
    <form action="." method="post">
        {% csrf_token %}
        {{ formset.management_form }}
        {{ formset.non_field_errors }}
        <table class="table table-bordered table_list">
            <thead>
                <tr class="table_title">
                    <th>{% trans 'Clinical Trial' %}</th>
                    <th>{% trans 'Holder' %}</th>
                </tr>
            </thead>
            <tbody>
                {% for form in formset %}
                    <tr class="table_style">
                        <td>{{ form.id }}<a target="_blank" href="{% url 'clinical_trial_detail' form.instance.id %}">{{ form.instance }}</a></td>
                        <td>{{ form.holder.errors }}{{ form.holder }}</td>
                    </tr>
                {% empty %}
                    <tr class="table_style">
                        <td colspan="2">{% trans 'No clinical trials without holder' %}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <input type="submit" value="{% trans 'Save' %}" class=" button btn btn-success">
    </form>

    <div class="pagination">
        <span class="step-links">
            {% if current_page.has_previous %}
                <form action="." method="get">
                    {% if search_form.user.value %}
                        <input type="hidden" name="user" value="{{ search_form.user.value }}">
                    {% endif %}
                    {% if search_form.group.value %}
                        <input type="hidden" name="group" value="{{ search_form.group.value }}">
                    {% endif %}
                    <input type="hidden" name="page" value="{{ current_page.previous_page_number }}">
                    <input type="submit" class="btn btn-info" value="{% trans 'Previous' %}">
                </form>
            {% endif %}
            {% if current_page.number == 1 and current_page.paginator.num_pages == 1 %}
            {% else %}
                <span class="current">
                    {% trans 'Page' %} {{ current_page.number }} {% trans 'of' %} {{ current_page.paginator.num_pages }}
                </span>
            {% endif %}

            {% if current_page.has_next %}
                <form action="." method="get">
                    {% if search_form.user.value %}
                        <input type="hidden" name="user" value="{{ search_form.user.value }}">
                    {% endif %}
                    {% if search_form.group.value %}
                        <input type="hidden" name="group" value="{{ search_form.group.value }}">
                    {% endif %}
                    <input type="hidden" name="page" value="{{ current_page.next_page_number }}">
                    <input type="submit" class="btn btn-info" value="{% trans 'Next' %}">
                </form>
            {% endif %}
        </span>
    </div>

{% endblock administration_content %}

{% block extrascripts %}
<script type="text/javascript">
  function get_url_parameters (term, page, context) {
      var field_id = jQuery(this).data('field_id'),
        res = {
          'term': term,
          'page': page,
          'context': context,
          'group_id': $(this).parent().next().find('[id*=group][type=hidden]').val()
        };
      if (field_id) {
        res['field_id'] = field_id;
      }
      return res;
    }
</script>
{% endblock %}

templates/clinical_trials/clinicaltrial_confirm_delete.html
{% extends "administration/base_administration.html" %}
{% load i18n %}

{% block breadcrumbs %}
{{ block.super }}
<li class="formTab">
    <div>
        <a href="{% url "clinical_trial_edit_list" object.id %}">
            {% trans "Clinical Trial" %}
        </a>
    </div>
</li>
<li class="formTab">
    <div class="selected">
        {% trans "Confirm Decision" %}
    </div>
</li>
{% endblock %}
{% block administration_content %}
{% if request.is_ajax %}
	<a class="close" data-dismiss="modal"><img src="/static/img/close.png" /></a>
{% endif %}
<form action="{{ request.path }}" method="post">
    {% csrf_token %}
    <p>{% trans 'Are you sure you want to delete' %} "{{ object }}"?</p>
    <input class="confirm_delete" type="submit" value="{% trans 'Confirm' %}" />
    <a href="{% url 'home' %}" class="no_delete">{% trans "No" %}</a>
</form>

{% endblock administration_content %}

templates/clinical_trials/email_adm_approved_trial.html
{% load i18n %}
{% blocktrans %}
Hello,
The clinical trial has been <b>approved</b>.

To view the clinical trial: <a href="{{ site_url }}{{ trial.get_absolute_url }}">Click here</a>
{% endblocktrans %}

templates/clinical_trials/modal-field-registrant.html
<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true" id="field-registrant-modal" >
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
        </div>
    </div>
</div>